### ISSUE TITLE
Structure Issue

### ISSUE THREAD

**Issue by Hiltronix** [taxigps/plugin.program.utorrent#6]
Hello,

I'd like to say that I have been using this addon for a while now, and it's great, it's been very useful to me.  Thank you for sharing it.

I have submitted two pull requests to fix issues I've encountered.  One with simplejson that causes this addon to not function on Android devices.  

The other PR issue seems to be from a typo that does not exist on the version on the Kodi Official Repo, but does exist here on GitHub.

But there is a third issue.  If you download the ZIP file from your GitHub repo, the ZIP file has one too many directories in the file structure to allow it to be installed directly into Kodi/XBMC.  The ZIP file has to be manually restructured to remove this directory, or Kodi/XBMC will not install the addon, and causes a bad structure error.

I would suggest that you remove the addon directory/folder name from the GitHub repo.  Your repo is already named after the addon name, so having a directory in this repo that is also called "plugin.program.utorrent" causes problems.  So the ZIP file ens up with a structure of "plugin.program.utorrent\plugin.program.utorrent\resources...".  And resources and related files all need to be one level up.

Thanks and have a great day.

**Comment by taxigps** [comment]
thanks for the patches. and the zip file download here is the source code pack, not a install zip file.
